### ISSUE TITLE
数据库连接报错

### ISSUE THREAD

**Issue by mgjuc** [oldme-git/star#3]
manifest\config\config.yaml
``` yaml
server:
    address: ":8000"
    openapiPath: "/api.json"
    swaggerPath: "/swagger"

database:
  default:
    link:   "mysql:root:root@tcp(192.168.187.132:3306)/star?loc=Local"
    debug:  true
```
报错如下，看起来 PingMaster 的配置和link不一样。
![Image](https://github.com/user-attachments/assets/31cb59b5-ae3b-496d-bbfb-e58f050d2f9c)
